print ("")
print ("hey twin")
input ()
name = input("what is your name ")
print ("wanna hear a joke")
answer = input ("")
print ("i dont care")
input ()
print ("why didnt the chicken cross the road")
input ()
print ("because it got hit by a car")
input ()
print (f"what a joke right {name}")
input ()
print (f"right {name}")
input ()
print ("wanna hear another joke")
answer2 = input ("")
print ("")
print ("why did the chicken cross the road")
input ()
print ("because it didnt get hit by a car")
input ()
print ("what a knee slapper")
input ()
print ("right?")
input ()
print (f"{name}?")
input ()                                                                                                                                                         