print ("")
print ("hey twin")
input ()
print ("Madlibs")
input ()
adjective1 = input("choose an adjective ")
noun1 = input("choose a noun ")
verbed1 = input("choose a verb ending in ed (closed) ")
place1 = input("choose a place ")
pluralnoun1 = input("choose a plural noun ")
noun2 = input("choose a noun ")
exclamation1 = input("choose a exclamation ")
adverb1 = input("choose a adverb (like quickly) ")
verbing1 = input("choose a verb ending in ing ")
adjective2 = input("choose a adjective ")
number = input ("choose a number ")
adjective3 = input ("choose a adjective ")
pluralnoun2 = input ("choose a plural noun ")
pluralnoun3 = input ("choose another plural noun ")
print ("")
print (f"the very {adjective1} {noun1} walked into {place1}.")
input ()
print (f"in there, the {noun1} saw lots of {pluralnoun1} {verbing1} around.")
input ()
print (f"{exclamation1}! the {noun1} was then {adverb1} {verbed1} by a {adjective2} {noun2}.")
input()
print (f"{number} years later, {noun1} died in a accident involving {pluralnoun2} and {pluralnoun3}.")
input ()
print (f"the {noun2} is now the most {adjective3} {noun2} ever")
input ()
answer = input ("did ya like it (yes or no) ")
if answer == "yes":
    print ("yay")
else: 
    print ("ok bye")
